FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["FAL/FAL.csproj","FAL/"]
COPY ["FAL/Share.csproj","Share/"]
RUN dotnet restore "FAL/FAL.csproj" 
COPY . .
WORKDIR "/src/FAL"
RUN dotnet build "FAL.csproj" -c $BUILD_CONFIGURATION -o /app/build 

FROM build as publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "FAL/FAL.csproj" - c $BUILD_CONFIGURATION -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet","FAL.dll"]
